# Gradle properties
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
# org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
org.gradle.console=rich
org.gradle.warning.mode=all

maven_version=15.8.3-SNAPSHOT
paperVersion=1.8-1.21.10
velocityVersion=3.0-3.4
waterfallVersion=1.17-1.21
modMcVersion=1.21.10
