# Gradle properties
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
# org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
org.gradle.console=rich
org.gradle.warning.mode=all

maven_version=15.9.2-SNAPSHOT
paperVersion=1.8-1.21.11
velocityVersion=3.0-3.4
waterfallVersion=1.17-1.21

# Minecraft properties
modMcVersion=1.21.11

# Dependencies
architectury_api_version = 19.0.1
fabric_loader_version = 0.18.4
fabric_api_version=0.140.2+1.21.11
neoforge_version=21.11.17-beta
