# Gradle properties
org.gradle.jvmargs=-Xmx4G -Xms256m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

org.gradle.daemon=true

org.gradle.configureondemand=true
org.gradle.cache=true
org.gradle.caching=true
org.gradle.parallel=true

org.gradle.vfs.watch=true
maven_version=15.7.8-SNAPSHOT
paperVersion=1.8-1.21.7
velocityVersion=3.0-3.4
waterfallVersion=1.17-1.21
modMcVersion=1.21.7
