name: ${project.name}
main: skinsrestorer.bukkit.SkinsRestorer
version: ${project.version}
description: ${project.description}
website: https://skinsrestorer.net/
authors: [Th3Tr0LLeR, McLive, DoNotSpamPls, knat]
softdepend: ["ViaBackwards"]
api-version: 1.13
commands:
  skin:
    description: Main command.
  sr:
    aliases: [skinsrestorer]
    description: Admin commands.
  skins:
    description: Opens skins GUI
permissions:
   skinsrestorer.command:
     description: Allows access to the main "/skin" commands.
     default: op   
   skinsrestorer.command.set:
     description: Allows access to change your skin.
     default: op
   skinsrestorer.command.clear:
     description: Allows access to clear your skin.
     default: op
   skinsrestorer.command.update:
     description: Allows access to update your skin.
     default: op
     
   skinsrestorer.admincommand:
     description: Allows access to the main "/sr" commands.
     default: op    
   skinsrestorer.command.set.other:
     description: Allows access to set a player skin.
     default: op
   skinsrestorer.command.clear.other:
     description: Allows access to clear a player skin.
     default: op 
   skinsrestorer.command.update.other:
     description: Allows access to update a player skin.
     default: op 
   skinsrestorer.admincommand.status:
     description: Allows access to /sr status.
     default: op 
   skinsrestorer.admincommand.drop:
     description: Allows access to removes a .SKIN file.
     default: op
   skinsrestorer.admincommand.props:
     description: Allows access to get the skinprops of a player.
     default: op 
     
   skinsrestorer.bypasscooldown:
     description: Bypasses any set cooldowns in the config.
     default: op
   skinsrestorer.bypassdisabled:
     description: Allows access to disabled skins in the config.
     default: op
