name: SkinsRestorer
main: net.skinsrestorer.bukkit.SRBukkitBootstrap
version: ${version}
description: ${description}
website: https://skinsrestorer.net/
authors: [ "knat", "AlexProgrammerDE", "Th3Tr0LLeR", "McLive", "DoNotSpamPls" ]
softdepend: [ "ProtocolLib", "ViaVersion", "ViaBackwards", "ProtocolSupport", "MundoSK" ]
api-version: 1.13
folia-supported: true
