name: ðŸž Bug
description: File a bug/issue report
labels: [ðŸ› bug]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.

        Tip: You can go to the [GitHub issue tab](https://github.com/SkinsRestorer/SkinsRestorerX/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+%3Abug%3A+bug%22) for a list of open issues
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: download
    attributes:
      label: Are you using forge?
      description: "If you don't know what forge is, awnser no"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Installed conforming to our guide?
      description: |
        Please check conduct our installation guide and check if all step's have been performed at [SkinsRestorer/Wiki/Installation](https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Installing-SkinsRestorer#Basic-Installation)
        
        Unsure or have questions? -> Ask in our [SkinsRestorer discord server](https://skinsrestorer.net/discord)
      options:
      - label: I have read the installation guide and performed all steps
        required: true
  - type: textarea
    attributes:
      label: Describe your issue
      description: What is the issue?
      placeholder: "After the update x feature broke. It gives me this message: '...'"
    validations:
      required: true
  - type: textarea
    attributes:
      label: How can we reproduce what you got?
      description: Please describe the steps for us to reproduce the issue. Screenshots are also very welcomed.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: input
    id: logs
    attributes:
      label: Server/Error Logs
      description: |
        Replace the links below by a paste of your startup logs (If you run a Bungeecord/Velocity server, please send startup logs from Proxy AND Spigot/Bukkit)
        - https://gist.github.com
        - https://bin.birdflop.com
      placeholder: "<log url>"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "----"
  - type: markdown
    attributes:
      value: "## Server info"
  - type: textarea
    attributes:
      label: Minecraft implementation
      description: |
        Use /version, /bungee or /velocity to get the version!
        Examples: 
          - **Proxy**: This server is running BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a17d8f8:1634
          - **Backend**: This server is running Paper version git-Paper-220 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 63aa4d3)
          
          TIP: If you don't use a proxy (like BungeeCord, Waterfall or Velocity) or don't know what this means? Then you can ignore the proxy part.
      value: |
          - Proxy: 
          - Backend: 
      render: markdown
    validations:
      required: false
  - type: input
    id: client
    attributes:
      label: What client are you using?
      description: |
        What client are you using to start Minecraft? Vanilla Launcher, MultiMC Cracked, TLauncher, etc.
        TLaunchers built-in skin mod is known to cause issues with SkinsRestorer.
      render: markdown
    validations:
      required: false
  - type: input
    id: srversion
    attributes:
      label: SkinsRestorer Version
      description: "SkinsRestorer says it's version at startup."
      placeholder: "14.2.4"
    validations:
      required: true
  - type: input
    id: plugins
    attributes:
      label: List of plugins
      description: "Go to your server and run **/plugins**, then copy and paste the list here."
      placeholder: "Example: Plugins (5): Essentials, EssentialsChat, LuckPerms, SkinsRestorer, WorldEdit"
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: Java Version
      description: "Often servers say the java version at startup. You can also execute `java -version` in your machine terminal. (Not of Minecraft Server)"
      placeholder: "openjdk version 17.0.5 2022-10-18"
    validations:
      required: true
  - type: dropdown
    id: thirdpartyplugin
    attributes:
      label: Does your issue require a plugin in order to reproduce?
      description: "Sometimes SkinsRestorer collides with other plugins, have you found the colliding plugin then say yes"
      options:
        - "Yes"
        - "No"
    validations:
      required: false
