/*
 * SkinsRestorer
 * Copyright (C) 2024  SkinsRestorer Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package net.skinsrestorer.shared.config;

import ch.jalu.configme.Comment;
import ch.jalu.configme.SettingsHolder;
import ch.jalu.configme.properties.Property;

import static ch.jalu.configme.properties.PropertyInitializer.newProperty;

public class APIConfig implements SettingsHolder {
    @Comment({
            "Here you can fill in your APIKey for lower MineSkin request times.",
            "Key can be requested from https://mineskin.org/apikey",
            "MineSkin offers 10% off your first three months (all plans except Lite) with the coupon SKINSRESTORER10.",
            "All plans other than Lite include cape generation, higher limits, and other exclusive features.",
            "[?] A key is not required, but recommended."
    })
    public static final Property<String> MINESKIN_API_KEY = newProperty("api.mineskinAPIKey", "key");
    @Comment({
            "SkinsRestorer uses MineSkin to generate usable skins from links.",
            "All skins generated by MineSkin are by default shown in their public gallery on their website.",
            "Enabling this option will hide all skins generated by MineSkin from their public gallery.",
    })
    public static final Property<Boolean> MINESKIN_SECRET_SKINS = newProperty("api.mineskinSecretSkins", false);
    @Comment({
            "SkinsRestorer provides curated recommended skins for players to use",
            "These skin can be used via /skin random and the /skins GUI",
            "If you would like to opt out of this feature, set this to false.",
            "It will prevent loading of recommended skins from storage and downloading new ones.",
            "Be aware that commands like /skin random will not work without this feature."
    })
    public static final Property<Boolean> FETCH_RECOMMENDED_SKINS = newProperty("api.fetchRecommendedSkins", true);
    @Comment({
            "Window size in seconds for batching Mojang API requests to avoid rate limits.",
            "Requests are batched in windows of this duration or up to 10 requests, whichever comes first.",
            "Default is 1 second."
    })
    public static final Property<Integer> MOJANG_BATCH_WINDOW_SECONDS = newProperty("api.mojangBatchWindowSeconds", 1);
}
