/*
 * SkinsRestorer
 * Copyright (C) 2024  SkinsRestorer Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package net.skinsrestorer.shared.config;

import ch.jalu.configme.Comment;
import ch.jalu.configme.SettingsHolder;
import ch.jalu.configme.properties.Property;

import static ch.jalu.configme.properties.PropertyInitializer.newProperty;

public class APIConfig implements SettingsHolder {
    @Comment({
            "Here you can fill in your APIKey for lower MineSkin request times.",
            "Key can be requested from https://mineskin.org/apikey",
            "[?] A key is not required, but recommended."
    })
    public static final Property<String> MINESKIN_API_KEY = newProperty("api.mineskinAPIKey", "key");
    @Comment({
            "SkinsRestorer uses MineSkin to generate usable skins from links.",
            "All skins generated by MineSkin are by default shown in their public gallery on their website.",
            "Enabling this option will hide all skins generated by MineSkin from their public gallery.",
    })
    public static final Property<Boolean> MINESKIN_SECRET_SKINS = newProperty("api.mineskinSecretSkins", false);
}
